# Form implementation generated from reading ui file 'inicioSesion.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

#prueba de comentario
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 528)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 30, 751, 461))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.ingresar = QtWidgets.QPushButton(parent=self.frame)
        self.ingresar.setGeometry(QtCore.QRect(290, 370, 75, 24))
        self.ingresar.setObjectName("ingresar")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(250, 20, 201, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 250, 91, 21))
        self.label_3.setObjectName("label_3")
        self.usuario = QtWidgets.QTextEdit(parent=self.frame)
        self.usuario.setGeometry(QtCore.QRect(210, 100, 321, 51))
        self.usuario.setObjectName("usuario")
        self.clave = QtWidgets.QTextEdit(parent=self.frame)
        self.clave.setGeometry(QtCore.QRect(220, 240, 321, 51))
        self.clave.setObjectName("clave")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ingresar.setText(_translate("MainWindow", "INGRESAR"))
        self.label.setText(_translate("MainWindow", "AULA VIRTUAL GOTITAS DEL SABER"))
        self.label_2.setText(_translate("MainWindow", "USUARIO"))
        self.label_3.setText(_translate("MainWindow", "CONTRASEÑA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
